i3-config: /home/hiepph/.config/i3/config
polybar-config: /home/hiepph/.config/polybar/config
xresources: /home/hiepph/.Xresources
nitrogen-config: /home/hiepph/.config/nitrogen/bg-saved.cfg
wallpaper-path: /home/hiepph/.config/nitrogen/
